### PR TITLE
Improves menu selection mechanics (regular vim)

### PR DESCRIPTION
**Pull request by dsabsay**
This fixes the issue described in #58.  When opening the popup window, the cursor is now moved to the first link item in the list. Additionally, when `j`/`k` are pressed, any non-link menu items are skipped over.

I've implemented and tested with regular terminal vim 8.2. I'm not sure if Neovim had this problem or not.

### CODE REVIEW

**Comment by airblade** [comment]
Solves the problem for me (Vim 8.2) – thanks @dsabsay!

**Comment by tristandunn** [comment]
Works for me in vim 8.2.1750 as well and honestly makes the plug-in a 100% more useful. Would be great to get this merged.

Thanks @dsabsay!

**Comment by pechorin** [comment]
Sorry for delay, thanks for work, but this doesn't work in this scenario:

Снимок экрана 2020-12-08 в 02 03 53

I can't select [10 more]


Also it's stop working on long lists (more then ~30 items)

Снимок экрана 2020-12-08 в 02 05 34

Sorry for big delay, i think where will no problem with pull requests now.

**Comment by pechorin** [comment]
Also, cursor starting position fixed in https://github.com/pechorin/any-jump.vim/pull/79

**Pull request merged**
